# Site settings
title: Mikael's Site
email: me223fn@student.lnu.se
#description: > # this means to ignore newlines until "baseurl:"
#  Welcome to my site! My name is Mikael Eriksson (Mirke on Github)
#  and I study development and maintenance of software systems.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: mirke_coding
github_username:  Mirke

# Build settings
markdown: kramdown
